import * as getStdin from "get-stdin";
import {readFileSync} from "fs";
import {main} from "@angular/compiler-cli/src/main";

// reads license information such as generated by `license-checker --json` (https://github.com/davglass/license-checker)
// and applies manual tweaks to the results based on case-by-case research in an attempt to be fully compliant with all
// dependency licenses, and outputs the results

console.error("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ "+(new Date()));
getStdin().then((s: string) => {
  let licensedDependencies = {};
  let dependencyInfo = JSON.parse(s.replace(/\\r\\n/g, "\\n").replace(/&gt;/g, ">").replace(/&lt;/g, "<"));
  console.error("Done processing input.");
  console.error("==========================================");
  let mainInfo = null;

  for (let key in dependencyInfo) {
    console.error("-------- processing "+key);
    if (!dependencyInfo.hasOwnProperty(key)) {
      continue;
    }
    let dependency = dependencyInfo[key];
    if (dependency.name === "narrative-intervention") {
      mainInfo = dependency;
      dependency.copyrightSwap = "Copyright (c) <year> <copyright holders>";
    } else {
      dependency.owners = require('child_process').execSync(`npm owner ls ${dependency.name}`).toString().trim().split('\n').join(', ');
    }

    let chosenLicense = null;

    switch (dependency.repository) {

      case "https://github.com/DefinitelyTyped/DefinitelyTyped":
        if (dependency.copyright == null) {
          dependency.copyright = "Copyrights are respective of each contributor listed at the beginning of each definition file.";
        }
        break;

      case "https://github.com/angular/angular":
        dependency.copyright = "Copyright (c) 2014-2017 Google, Inc. http://angular.io";
        break;

      case "https://github.com/ionic-team/ionic-native":
        dependency.copyright = "Copyright 2015-present Drifty Co. http://drifty.com/";
        break;
    }

    if (dependency.copyright == null && dependency.licenseText) {
      let parts = dependency.licenseText.split('\n');
      for (let part of parts) {
        part = part.trim();
        let i = 0;
        while ("#_*>- \t".indexOf(part[i]) != -1) {
          i++;
        }
        part = part.substr(i);
        if (dependency.copyright) {
          if (part.toLowerCase().startsWith("all rights reserved")) {
            if (dependency.copyright.slice(-1) != ".") {
              dependency.copyright += '.';
            }
            dependency.copyright += " " + part;
          }
          break;
        }
        if (part.toLowerCase().startsWith("copyright")) {
          dependency.copyright = part;
        }
      }
    } else if (dependency.copyright.toLowerCase().indexOf(".. all rights") != -1) {
      dependency.copyright = dependency.copyright.replace(".. ", ". ");
    }

    switch (key) {
      case "babel-code-frame@6.26.0":
      case "babel-runtime@6.26.0":
      case "bcrypt-pbkdf@1.0.1":
      case "big-integer@1.6.12":
      case "browserify-cipher@1.0.0":
      case "browserify-des@1.0.0":
      case "browserify-zlib@0.1.4":
      case "create-ecdh@4.0.0":
      case "create-hash@1.1.3":
      case "create-hmac@1.1.6":
      case "diffie-hellman@5.0.2":
      case "electron-to-chromium@1.3.27":
      case "error@7.0.2":
      case "estree-walker@0.3.1":
      case "estree-walker@0.5.0":
      case "falafel@1.2.0":
      case "get-caller-file@1.0.2":
      case "hash-base@2.0.2":
      case "inline-process-browser@1.0.0":
      case "jsonify@0.0.0":
      case "loader-runner@2.3.0":
      case "magic-string@0.22.4":
      case "parse-asn1@5.1.0":
      case "public-encrypt@4.0.0":
      case "raf@3.4.0":
      case "remove-trailing-separator@1.1.0":
      case "rollup-plugin-node-resolve@3.0.0":
      case "rollup-pluginutils@2.0.1":
      case "sass-graph@2.2.4":
      case "spdx-license-ids@1.2.2":
      case "tapable@0.2.8":
      case "ionic-angular@3.9.2":
      case "meteor-typings@1.4.1":
      case "minimalistic-assert@1.0.0":
      case "tweetnacl@0.14.5":
      case "typescript-extends@1.0.1":
      case "concat-map@0.0.1":
      case "fast-json-stable-stringify@2.0.0":
      case "https-browserify@0.0.1":
      case "is-typedarray@1.0.0":
      case "json-stable-stringify@1.0.1":
      case "minimist@0.0.8":
      case "minimist@1.2.0":
      case "resolve@1.1.7":
      case "resolve@1.5.0":
      case "tty-browserify@0.0.0":
      case "vm-browserify@0.0.4":
        dependency.copyright = false;
        break;

      case "tunnel-agent@0.6.0":
      case "oauth-sign@0.8.2":
      case "spdx-correct@1.0.2":
      case "aws-sign2@0.6.0":
      case "aws-sign2@0.7.0":
      case "caseless@0.12.0":
      case "cordova-common@1.1.0":
      case "cordova-plugin-kiosk@1.0.0":
      case "forever-agent@0.6.1":
      case "validate-npm-package-license@3.0.1":
        dependency.copyright = false;
        dependency.notice = false;
        break;

      case "jstransform@3.0.0":
        dependency.copyright = "Copyright 2013 Facebook, Inc.";
        dependency.notice = false;
        break;

      case "detect-libc@1.0.2":
        dependency.copyright = "Copyright 2017 Lovell Fuller";
        dependency.notice = false;
        break;

      case "elementtree@0.1.6":
      case "elementtree@0.1.7":
        dependency.copyright = "Copyright 2011 Rackspace";
        chosenLicense = "Apache-2.0";
        break;

      case "cordova-registry-mapper@1.1.15":
      case "ionic-plugin-keyboard@2.2.1":
        dependency.copyright = false;
        chosenLicense = "Apache-2.0";
        dependency.notice = false;
        break;

      case "localforage-cordovasqlitedriver@1.5.0":
        chosenLicense = "Apache-2.0";
        dependency.notice = false;
        break;

      case "q@1.4.1":
        dependency.copyright = "Copyright 2009–2014 Kristopher Michael Kowal. All rights reserved.";
        break;

      case "q@1.5.1":
        dependency.copyright = "Copyright 2009–2017 Kristopher Michael Kowal. All rights reserved.";
        break;

      case "nan@2.6.2":
      case "nan@2.7.0":
        dependency.copyright = "Copyright (c) 2017 NAN contributors.";
        break;

      case "isstream@0.1.2":
        dependency.copyright = "Copyright (c) 2015 Rod Vagg.";
        break;

      case "path-browserify@0.0.0":
      case "stream-browserify@2.0.1":
        dependency.copyright = "Copyright Joyent, Inc. and other Node contributors.";
        break;

      case "async-each@1.0.1":
        dependency.copyright = "Copyright (c) 2016 Paul Miller (paulmillr.com)";
        break;

      case "file-saver@1.3.8":
        dependency.copyright = "Copyright © 2016 Eli Grey http://eligrey.com";
        break;

      case "doctrine@0.7.2":
      case "esprima-fb@15001.1001.0-dev-harmony-fb":
      case "esprima-fb@3001.1.0-dev-harmony-fb":
        dependency.copyright = false;
        chosenLicense = "BSD-2-Clause";
        break;

      case "domain-browser@1.1.7":
        dependency.copyright = "Unless stated otherwise all works are: Copyright © 2013+ Bevry Pty Ltd";
        break;

      case "escope@3.6.0":
        dependency.copyright = "Copyright (C) 2012-2013 Yusuke Suzuki (twitter: @Constellation) and other contributors.";
        break;

      case "esutils@1.1.6":
      case "esutils@2.0.2":
        dependency.copyright = "Copyright (C) 2013 Yusuke Suzuki (twitter: @Constellation) and other contributors.";
        chosenLicense = "BSD-2-Clause";
        break;

      case "esmangle-evaluator@1.0.1":
        dependency.copyright = "Copyright (C) 2012 Yusuke Suzuki <utatane.tea@gmail.com> Copyright (C) 2012 Ariya Hidayat <ariya.hidayat@gmail.com>";
        break;

      case "estraverse@4.2.0":
        dependency.copyright = "Copyright (C) 2012-2013 Yusuke Suzuki <utatane.tea@gmail.com> Copyright (C) 2012 Ariya Hidayat <ariya.hidayat@gmail.com>";
        break;

      case "get-stdin@4.0.1":
      case "invert-kv@1.0.0":
      case "is-path-cwd@1.0.0":
      case "is-path-in-cwd@1.0.0":
      case "set-immediate-shim@1.0.1":
        dependency.copyright = "© Sindre Sorhus";
        break;

      case "shelljs@0.5.3":
      case "sntp@1.0.9":
      case "sntp@2.1.0":
      case "source-map@0.1.31":
        chosenLicense = "BSD-3-Clause";
        break;

      case "json-schema@0.2.3":
        chosenLicense = "BSD-3-Clause";
        dependency.copyright = "Copyright (c) 2005-2017, JS Foundation All rights reserved.";
        break;

      case "Base64@0.2.1":
        chosenLicense = "WTFPL-2.0";
        break;

      case "path-parse@1.0.5":
        dependency.copyright = "© Javier Blanco";
        break;

      case "properties-parser@0.2.3":
      case "xmldom@0.1.22":
      case "indexof@0.0.1":
        dependency.copyright = false;
        chosenLicense = "MIT";
        break;

      case "wordwrap@0.0.2":
        dependency.copyright = false;
        chosenLicense = "X11";
        break;

      case "reflect-metadata@0.1.10":
      case "tslib@1.8.0":
        dependency.copyright = "Copyright (c) Microsoft Corporation. All rights reserved.";
        dependency.notice = false;
        break;

      case "typescript@2.6.1":
        dependency.copyright = "Copyright (c) Microsoft Corporation. All rights reserved.";
        dependency.noticeFile = `${dependency.path}/ThirdPartyNoticeText.txt`;
        break;

      case "regenerator-runtime@0.11.0":
        dependency.copyright = false;
        dependency.notice = "Exception: this project contains a file (runtime.js) with the following copyright:\n" +
          "Copyright (c) 2014-present, Facebook, Inc.";
        break;

      case "request@2.81.0":
      case "request@2.83.0":
        dependency.copyright = "Copyright 2010-2012 Mikeal Rogers";
        dependency.notice = false;
        break;

      case "sw-toolbox@3.6.0":
        dependency.copyright = "Copyright 2015-2016 Google, Inc.";
        dependency.notice = false;
        break;

      case "tslint@5.8.0":
        dependency.copyright = "Copyright 2013 Palantir Technologies, Inc.";
        dependency.notice = false;
        break;

      case "getpass@0.1.7":
      case "http-signature@1.1.1":
      case "http-signature@1.2.1":
      case "sshpk@1.13.0":
      case "sshpk@1.13.1":
        dependency.copyright = "Copyright Joyent, Inc. All rights reserved.";
        break;

      case "assert@1.4.1":
      case "readable-stream@1.0.34":
      case "util@0.10.3":
        dependency.copyright = "Copyright Joyent, Inc. and other Node contributors. All rights reserved.";
        break;

      case "abbrev@1.1.1":
        dependency.copyright = "Copyright (c) Isaac Z. Schlueter and Contributors";
        break;

      case "amdefine@1.0.1":
        dependency.copyright = "Copyright (c) 2011-2016, The Dojo Foundation";
        chosenLicense = "MIT";
        break;

      case "localforage@1.4.3":
      case "rxjs@5.5.2":
        dependency.notice = false;
        break;

      case "source-map@0.4.4":
        dependency.copyright = "Copyright 2011 Mozilla Foundation and contributors";
        break;

      case "tough-cookie@2.3.2":
      case "tough-cookie@2.3.3":
        dependency.notice = "===\n" +
          "\n" +
          "The following exceptions apply:\n" +
          "\n" +
          "===\n" +
          "\n" +
          "`public_suffix_list.dat` was obtained from\n" +
          "<https://publicsuffix.org/list/public_suffix_list.dat> via\n" +
          "<http://publicsuffix.org>. The license for this file is MPL/2.0.  The header of\n" +
          "that file reads as follows:\n" +
          "\n" +
          "  // This Source Code Form is subject to the terms of the Mozilla Public\n" +
          "  // License, v. 2.0. If a copy of the MPL was not distributed with this\n" +
          "  // file, You can obtain one at http://mozilla.org/MPL/2.0/.\n" +
          "\n" +
          "===\n" +
          "For convenience, here is a copy of the Mozilla Public License, v. 2.0:\n" +
          "===\n" +
          "\n" +
          "Mozilla Public License, version 2.0 1. Definitions 1.1. “Contributor” means each individual or legal entity that creates, contributes to the creation of, or owns Covered Software.\n" +
          "\n" +
          "1.2. “Contributor Version” means the combination of the Contributions of others (if any) used by a Contributor and that particular Contributor’s Contribution.\n" +
          "\n" +
          "1.3. “Contribution” means Covered Software of a particular Contributor.\n" +
          "\n" +
          "1.4. “Covered Software” means Source Code Form to which the initial Contributor has attached the notice in Exhibit A, the Executable Form of such Source Code Form, and Modifications of such Source Code Form, in each case including portions thereof.\n" +
          "\n" +
          "1.5. “Incompatible With Secondary Licenses” means\n" +
          "\n" +
          "that the initial Contributor has attached the notice described in Exhibit B to the Covered Software; or\n" +
          "\n" +
          "that the Covered Software was made available under the terms of version 1.1 or earlier of the License, but not also under the terms of a Secondary License.\n" +
          "\n" +
          "1.6. “Executable Form” means any form of the work other than Source Code Form.\n" +
          "\n" +
          "1.7. “Larger Work” means a work that combines Covered Software with other material, in a separate file or files, that is not Covered Software.\n" +
          "\n" +
          "1.8. “License” means this document.\n" +
          "\n" +
          "1.9. “Licensable” means having the right to grant, to the maximum extent possible, whether at the time of the initial grant or subsequently, any and all of the rights conveyed by this License.\n" +
          "\n" +
          "1.10. “Modifications” means any of the following:\n" +
          "\n" +
          "any file in Source Code Form that results from an addition to, deletion from, or modification of the contents of Covered Software; or\n" +
          "\n" +
          "any new file in Source Code Form that contains any Covered Software.\n" +
          "\n" +
          "1.11. “Patent Claims” of a Contributor means any patent claim(s), including without limitation, method, process, and apparatus claims, in any patent Licensable by such Contributor that would be infringed, but for the grant of the License, by the making, using, selling, offering for sale, having made, import, or transfer of either its Contributions or its Contributor Version.\n" +
          "\n" +
          "1.12. “Secondary License” means either the GNU General Public License, Version 2.0, the GNU Lesser General Public License, Version 2.1, the GNU Affero General Public License, Version 3.0, or any later versions of those licenses.\n" +
          "\n" +
          "1.13. “Source Code Form” means the form of the work preferred for making modifications.\n" +
          "\n" +
          "1.14. “You” (or “Your”) means an individual or a legal entity exercising rights under this License. For legal entities, “You” includes any entity that controls, is controlled by, or is under common control with You. For purposes of this definition, “control” means (a) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (b) ownership of more than fifty percent (50%) of the outstanding shares or beneficial ownership of such entity.\n" +
          "\n" +
          "2. License Grants and Conditions 2.1. Grants Each Contributor hereby grants You a world-wide, royalty-free, non-exclusive license:\n" +
          "\n" +
          "under intellectual property rights (other than patent or trademark) Licensable by such Contributor to use, reproduce, make available, modify, display, perform, distribute, and otherwise exploit its Contributions, either on an unmodified basis, with Modifications, or as part of a Larger Work; and\n" +
          "\n" +
          "under Patent Claims of such Contributor to make, use, sell, offer for sale, have made, import, and otherwise transfer either its Contributions or its Contributor Version.\n" +
          "\n" +
          "2.2. Effective Date The licenses granted in Section 2.1 with respect to any Contribution become effective for each Contribution on the date the Contributor first distributes such Contribution.\n" +
          "\n" +
          "2.3. Limitations on Grant Scope The licenses granted in this Section 2 are the only rights granted under this License. No additional rights or licenses will be implied from the distribution or licensing of Covered Software under this License. Notwithstanding Section 2.1(b) above, no patent license is granted by a Contributor:\n" +
          "\n" +
          "for any code that a Contributor has removed from Covered Software; or\n" +
          "\n" +
          "for infringements caused by: (i) Your and any other third party’s modifications of Covered Software, or (ii) the combination of its Contributions with other software (except as part of its Contributor Version); or\n" +
          "\n" +
          "under Patent Claims infringed by Covered Software in the absence of its Contributions.\n" +
          "\n" +
          "This License does not grant any rights in the trademarks, service marks, or logos of any Contributor (except as may be necessary to comply with the notice requirements in Section 3.4).\n" +
          "\n" +
          "2.4. Subsequent Licenses No Contributor makes additional grants as a result of Your choice to distribute the Covered Software under a subsequent version of this License (see Section 10.2) or under the terms of a Secondary License (if permitted under the terms of Section 3.3).\n" +
          "\n" +
          "2.5. Representation Each Contributor represents that the Contributor believes its Contributions are its original creation(s) or it has sufficient rights to grant the rights to its Contributions conveyed by this License.\n" +
          "\n" +
          "2.6. Fair Use This License is not intended to limit any rights You have under applicable copyright doctrines of fair use, fair dealing, or other equivalents.\n" +
          "\n" +
          "2.7. Conditions Sections 3.1, 3.2, 3.3, and 3.4 are conditions of the licenses granted in Section 2.1.\n" +
          "\n" +
          "3. Responsibilities 3.1. Distribution of Source Form All distribution of Covered Software in Source Code Form, including any Modifications that You create or to which You contribute, must be under the terms of this License. You must inform recipients that the Source Code Form of the Covered Software is governed by the terms of this License, and how they can obtain a copy of this License. You may not attempt to alter or restrict the recipients’ rights in the Source Code Form.\n" +
          "\n" +
          "3.2. Distribution of Executable Form If You distribute Covered Software in Executable Form then:\n" +
          "\n" +
          "such Covered Software must also be made available in Source Code Form, as described in Section 3.1, and You must inform recipients of the Executable Form how they can obtain a copy of such Source Code Form by reasonable means in a timely manner, at a charge no more than the cost of distribution to the recipient; and\n" +
          "\n" +
          "You may distribute such Executable Form under the terms of this License, or sublicense it under different terms, provided that the license for the Executable Form does not attempt to limit or alter the recipients’ rights in the Source Code Form under this License.\n" +
          "\n" +
          "3.3. Distribution of a Larger Work You may create and distribute a Larger Work under terms of Your choice, provided that You also comply with the requirements of this License for the Covered Software. If the Larger Work is a combination of Covered Software with a work governed by one or more Secondary Licenses, and the Covered Software is not Incompatible With Secondary Licenses, this License permits You to additionally distribute such Covered Software under the terms of such Secondary License(s), so that the recipient of the Larger Work may, at their option, further distribute the Covered Software under the terms of either this License or such Secondary License(s).\n" +
          "\n" +
          "3.4. Notices You may not remove or alter the substance of any license notices (including copyright notices, patent notices, disclaimers of warranty, or limitations of liability) contained within the Source Code Form of the Covered Software, except that You may alter any license notices to the extent required to remedy known factual inaccuracies.\n" +
          "\n" +
          "3.5. Application of Additional Terms You may choose to offer, and to charge a fee for, warranty, support, indemnity or liability obligations to one or more recipients of Covered Software. However, You may do so only on Your own behalf, and not on behalf of any Contributor. You must make it absolutely clear that any such warranty, support, indemnity, or liability obligation is offered by You alone, and You hereby agree to indemnify every Contributor for any liability incurred by such Contributor as a result of warranty, support, indemnity or liability terms You offer. You may include additional disclaimers of warranty and limitations of liability specific to any jurisdiction.\n" +
          "\n" +
          "4. Inability to Comply Due to Statute or Regulation If it is impossible for You to comply with any of the terms of this License with respect to some or all of the Covered Software due to statute, judicial order, or regulation then You must: (a) comply with the terms of this License to the maximum extent possible; and (b) describe the limitations and the code they affect. Such description must be placed in a text file included with all distributions of the Covered Software under this License. Except to the extent prohibited by statute or regulation, such description must be sufficiently detailed for a recipient of ordinary skill to be able to understand it.\n" +
          "\n" +
          "5. Termination 5.1. The rights granted under this License will terminate automatically if You fail to comply with any of its terms. However, if You become compliant, then the rights granted under this License from a particular Contributor are reinstated (a) provisionally, unless and until such Contributor explicitly and finally terminates Your grants, and (b) on an ongoing basis, if such Contributor fails to notify You of the non-compliance by some reasonable means prior to 60 days after You have come back into compliance. Moreover, Your grants from a particular Contributor are reinstated on an ongoing basis if such Contributor notifies You of the non-compliance by some reasonable means, this is the first time You have received notice of non-compliance with this License from such Contributor, and You become compliant prior to 30 days after Your receipt of the notice.\n" +
          "\n" +
          "5.2. If You initiate litigation against any entity by asserting a patent infringement claim (excluding declaratory judgment actions, counter-claims, and cross-claims) alleging that a Contributor Version directly or indirectly infringes any patent, then the rights granted to You by any and all Contributors for the Covered Software under Section 2.1 of this License shall terminate.\n" +
          "\n" +
          "5.3. In the event of termination under Sections 5.1 or 5.2 above, all end user license agreements (excluding distributors and resellers) which have been validly granted by You or Your distributors under this License prior to termination shall survive termination.\n" +
          "\n" +
          "6. Disclaimer of Warranty Covered Software is provided under this License on an “as is” basis, without warranty of any kind, either expressed, implied, or statutory, including, without limitation, warranties that the Covered Software is free of defects, merchantable, fit for a particular purpose or non-infringing. The entire risk as to the quality and performance of the Covered Software is with You. Should any Covered Software prove defective in any respect, You (not any Contributor) assume the cost of any necessary servicing, repair, or correction. This disclaimer of warranty constitutes an essential part of this License. No use of any Covered Software is authorized under this License except under this disclaimer.\n" +
          "\n" +
          "7. Limitation of Liability Under no circumstances and under no legal theory, whether tort (including negligence), contract, or otherwise, shall any Contributor, or anyone who distributes Covered Software as permitted above, be liable to You for any direct, indirect, special, incidental, or consequential damages of any character including, without limitation, damages for lost profits, loss of goodwill, work stoppage, computer failure or malfunction, or any and all other commercial damages or losses, even if such party shall have been informed of the possibility of such damages. This limitation of liability shall not apply to liability for death or personal injury resulting from such party’s negligence to the extent applicable law prohibits such limitation. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so this exclusion and limitation may not apply to You.\n" +
          "\n" +
          "8. Litigation Any litigation relating to this License may be brought only in the courts of a jurisdiction where the defendant maintains its principal place of business and such litigation shall be governed by laws of that jurisdiction, without reference to its conflict-of-law provisions. Nothing in this Section shall prevent a party’s ability to bring cross-claims or counter-claims.\n" +
          "\n" +
          "9. Miscellaneous This License represents the complete agreement concerning the subject matter hereof. If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable. Any law or regulation which provides that the language of a contract shall be construed against the drafter shall not be used to construe this License against a Contributor.\n" +
          "\n" +
          "10. Versions of the License 10.1. New Versions Mozilla Foundation is the license steward. Except as provided in Section 10.3, no one other than the license steward has the right to modify or publish new versions of this License. Each version will be given a distinguishing version number.\n" +
          "\n" +
          "10.2. Effect of New Versions You may distribute the Covered Software under the terms of the version of the License under which You originally received the Covered Software, or under the terms of any subsequent version published by the license steward.\n" +
          "\n" +
          "10.3. Modified Versions If you create software not governed by this License, and you want to create a new license for such software, you may create and use a modified version of this License if you rename the license and remove any references to the name of the license steward (except to note that such modified license differs from this License).\n" +
          "\n" +
          "10.4. Distributing Source Code Form that is Incompatible With Secondary Licenses If You choose to distribute Source Code Form that is Incompatible With Secondary Licenses under the terms of this version of the License, the notice described in Exhibit B of this License must be attached.\n" +
          "\n" +
          "Exhibit A - Source Code Form License Notice This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\n" +
          "\n" +
          "If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.\n" +
          "\n" +
          "You may add additional accurate notices of copyright ownership.\n" +
          "\n" +
          "Exhibit B - “Incompatible With Secondary Licenses” Notice This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.";
        break;

      case "async-foreach@0.1.3":
      case "base62@0.1.1":
      case "bytes@1.0.0":
      case "extsprintf@1.0.2":
      case "path-is-inside@1.0.2":
      case "rc@1.2.1":
      case "rc@1.2.2":
      case "spdx-expression-parse@1.0.4":
      case "stdout-stream@1.4.0":
      case "unorm@1.4.1":
      case "verror@1.3.6":
        chosenLicense = "MIT";
        break;

      case "cordova-plugin-device@1.1.4":
      case "cordova-plugin-splashscreen@4.0.3":
      case "cordova-plugin-whitelist@1.3.1":
        dependency.copyright = "Copyright 2012 The Apache Software Foundation";
        break;

      case "cordova-plugin-ionic-webview@1.1.16":
        dependency.copyright = false;
        dependency.notice = "The following copyright and license appears to apply to all files within the `src/ios` subdirectory:\n" +
          "Copyright (c) 2012 Niklas von Hertzen\n" +
          "\n" +
          "Permission is hereby granted, free of charge, to any person\n" +
          "obtaining a copy of this software and associated documentation\n" +
          "files (the \"Software\"), to deal in the Software without\n" +
          "restriction, including without limitation the rights to use,\n" +
          "copy, modify, merge, publish, distribute, sublicense, and/or sell\n" +
          "copies of the Software, and to permit persons to whom the\n" +
          "Software is furnished to do so, subject to the following\n" +
          "conditions:\n" +
          "\n" +
          "The above copyright notice and this permission notice shall be\n" +
          "included in all copies or substantial portions of the Software.\n" +
          "\n" +
          "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n" +
          "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\n" +
          "OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n" +
          "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\n" +
          "HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\n" +
          "WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n" +
          "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\n" +
          "OTHER DEALINGS IN THE SOFTWARE.\n";
        break;

      case "cordova-plugin-network-information@1.3.4":
        dependency.copyright = "Copyright 2012 The Apache Software Foundation";
        dependency.notice = "Apache Cordova\n" +
          "Copyright 2012 The Apache Software Foundation\n" +
          "\n" +
          "This product includes software developed at\n" +
          "The Apache Software Foundation (http://www.apache.org/).\n" +
          "\n" +
          "This product includes software developed by Apple Inc. License can be found in the header of the affected files. (src/ios/CDVReachability.h, src/ios/CDVReachability.m)\n" +
          "\n" +
          "---------------------------------------------------------------\n" +
          "\n" +
          "The aforementioned license to softwarre developed by Apple Inc is also included here for convenience:\n" +
          "\n" +
          "---------------------------------------------------------------\n" +
          "\n" +
          " Disclaimer: IMPORTANT:  This Apple software is supplied to you by Apple Inc.\n" +
          " (\"Apple\") in consideration of your agreement to the following terms, and your\n" +
          " use, installation, modification or redistribution of this Apple software\n" +
          " constitutes acceptance of these terms.  If you do not agree with these terms,\n" +
          " please do not use, install, modify or redistribute this Apple software.\n" +
          "\n" +
          " In consideration of your agreement to abide by the following terms, and subject\n" +
          " to these terms, Apple grants you a personal, non-exclusive license, under\n" +
          " Apple's copyrights in this original Apple software (the \"Apple Software\"), to\n" +
          " use, reproduce, modify and redistribute the Apple Software, with or without\n" +
          " modifications, in source and/or binary forms; provided that if you redistribute\n" +
          " the Apple Software in its entirety and without modifications, you must retain\n" +
          " this notice and the following text and disclaimers in all such redistributions\n" +
          " of the Apple Software.\n" +
          " Neither the name, trademarks, service marks or logos of Apple Inc. may be used\n" +
          " to endorse or promote products derived from the Apple Software without specific\n" +
          " prior written permission from Apple.  Except as expressly stated in this notice,\n" +
          " no other rights or licenses, express or implied, are granted by Apple herein,\n" +
          " including but not limited to any patent rights that may be infringed by your\n" +
          " derivative works or by other works in which the Apple Software may be\n" +
          " incorporated.\n" +
          "\n" +
          " The Apple Software is provided by Apple on an \"AS IS\" basis.  APPLE MAKES NO\n" +
          " WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED\n" +
          " WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n" +
          " PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN\n" +
          " COMBINATION WITH YOUR PRODUCTS.\n" +
          "\n" +
          " IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR\n" +
          " CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE\n" +
          " GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n" +
          " ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR\n" +
          " DISTRIBUTION OF THE APPLE SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF\n" +
          " CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF\n" +
          " APPLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n" +
          "\n" +
          " Copyright (C) 2010 Apple Inc. All Rights Reserved.";
        break;

      case "http-browserify@1.7.0":
        chosenLicense = "X11";
        break;

      case "caniuse-lite@1.0.30000760":
        dependency.copyright = false;
        dependency.notice = "The source of the data in this repo is caniuse.com";
        break;

      case "cordova-android@5.1.1":
        dependency.copyright = "Copyright 2015 The Apache Software Foundation";
        dependency.noticeFile = `${dependency.path}/NOTICE`;
        dependency.notice = "Apache Cordova\n" +
          "Copyright 2015 The Apache Software Foundation\n" +
          "\n" +
          "This product includes software developed at\n" +
          "The Apache Software Foundation (http://www.apache.org)\n" +
          "\n" +
          "=========================================================================\n" +
          "==  NOTICE file corresponding to the section 4 d of                    ==\n" +
          "==  the Apache License, Version 2.0,                                   ==\n" +
          "==  in this case for the Android-specific code.                        ==\n" +
          "=========================================================================\n" +
          "\n" +
          "This product includes software developed as part of\n" +
          "The Android Open Source Project (http://source.android.com).\n" +
          "\n" +
          "\n--------------------" +
          " ADDITIONAL LICENSES:\n" +
          "\n" +
          "================================================================================\n" +
          "bin/node_modules/q\n" +
          "================================================================================\n" +
          "\n" +
          "Copyright 2009–2012 Kristopher Michael Kowal. All rights reserved.\n" +
          "Permission is hereby granted, free of charge, to any person obtaining a copy\n" +
          "of this software and associated documentation files (the \"Software\"), to\n" +
          "deal in the Software without restriction, including without limitation the\n" +
          "rights to use, copy, modify, merge, publish, distribute, sublicense, and/or\n" +
          "sell copies of the Software, and to permit persons to whom the Software is\n" +
          "furnished to do so, subject to the following conditions:\n" +
          "\n" +
          "The above copyright notice and this permission notice shall be included in\n" +
          "all copies or substantial portions of the Software.\n" +
          "\n" +
          "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n" +
          "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n" +
          "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n" +
          "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n" +
          "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n" +
          "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS\n" +
          "IN THE SOFTWARE.\n" +
          "\n" +
          "================================================================================\n" +
          "bin/node_modules/shelljs\n" +
          "================================================================================\n" +
          "Copyright (c) 2012, Artur Adib <aadib@mozilla.com>\n" +
          "All rights reserved.\n" +
          "\n" +
          "You may use this project under the terms of the New BSD license as follows:\n" +
          "\n" +
          "Redistribution and use in source and binary forms, with or without\n" +
          "modification, are permitted provided that the following conditions are met:\n" +
          "    * Redistributions of source code must retain the above copyright\n" +
          "      notice, this list of conditions and the following disclaimer.\n" +
          "    * Redistributions in binary form must reproduce the above copyright\n" +
          "      notice, this list of conditions and the following disclaimer in the\n" +
          "      documentation and/or other materials provided with the distribution.\n" +
          "    * Neither the name of Artur Adib nor the\n" +
          "      names of the contributors may be used to endorse or promote products\n" +
          "      derived from this software without specific prior written permission.\n" +
          "\n" +
          "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" \n" +
          "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE \n" +
          "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE \n" +
          "ARE DISCLAIMED. IN NO EVENT SHALL ARTUR ADIB BE LIABLE FOR ANY\n" +
          "DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n" +
          "(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n" +
          "LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\n" +
          "ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n" +
          "(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF \n" +
          "THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n" +
          "\n" +
          "================================================================================\n" +
          "bin/node_modules/nopt\n" +
          "================================================================================\n" +
          "Copyright 2009, 2010, 2011 Isaac Z. Schlueter.\n" +
          "All rights reserved.\n" +
          "\n" +
          "Permission is hereby granted, free of charge, to any person\n" +
          "obtaining a copy of this software and associated documentation\n" +
          "files (the \"Software\"), to deal in the Software without\n" +
          "restriction, including without limitation the rights to use,\n" +
          "copy, modify, merge, publish, distribute, sublicense, and/or sell\n" +
          "copies of the Software, and to permit persons to whom the\n" +
          "Software is furnished to do so, subject to the following\n" +
          "conditions:\n" +
          "\n" +
          "The above copyright notice and this permission notice shall be\n" +
          "included in all copies or substantial portions of the Software.\n" +
          "\n" +
          "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n" +
          "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\n" +
          "OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n" +
          "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\n" +
          "HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\n" +
          "WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n" +
          "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\n" +
          "OTHER DEALINGS IN THE SOFTWARE.\n" +
          "\n" +
          "================================================================================\n" +
          "bin/node_modules/which\n" +
          "================================================================================\n" +
          "\n" +
          "Copyright 2009, 2010, 2011 Isaac Z. Schlueter.\n" +
          "All rights reserved.\n" +
          "\n" +
          "Permission is hereby granted, free of charge, to any person\n" +
          "obtaining a copy of this software and associated documentation\n" +
          "files (the \"Software\"), to deal in the Software without\n" +
          "restriction, including without limitation the rights to use,\n" +
          "copy, modify, merge, publish, distribute, sublicense, and/or sell\n" +
          "copies of the Software, and to permit persons to whom the\n" +
          "Software is furnished to do so, subject to the following\n" +
          "conditions:\n" +
          "\n" +
          "The above copyright notice and this permission notice shall be\n" +
          "included in all copies or substantial portions of the Software.\n" +
          "\n" +
          "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n" +
          "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\n" +
          "OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n" +
          "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\n" +
          "HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\n" +
          "WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n" +
          "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\n" +
          "OTHER DEALINGS IN THE SOFTWARE.";
        break;
    }

    let packagejson = JSON.parse(readFileSync(`${dependency.path}/package.json`).toString());
    let packagelicenses = packagejson.licenses;
    if (!packagelicenses) {
      packagelicenses = packagejson.license || null;
    }
    dependency.rawLicenses = packagelicenses;

    if (dependency.noticeFile) {
      if (dependency.notice == null) {
        dependency.notice = readFileSync(dependency.noticeFile).toString().trim();
      }
      dependency.noticeFile = dependency.noticeFile.replace(dependency.path, '.');
    }

    if (dependency.licenseFile) {
      dependency.licenseFile = dependency.licenseFile.replace(dependency.path, '.');
    }

    delete dependency.path;
    delete dependency.licenseText;
    if (chosenLicense == null) {
      chosenLicense = dependency.licenses;
    }
    if (dependency != mainInfo) {
      licensedDependencies[chosenLicense] = licensedDependencies[chosenLicense] || [];
      licensedDependencies[chosenLicense].push(dependency);
    }
  }
  console.error("==========================================");
  console.error("Processing output.");

  let counts = [];
  for (let dep in licensedDependencies) {
    let count = licensedDependencies[dep].length.toString();
    while (count.length < 4) {
      count = "0" + count;
    }
    counts.push(`${count}_${dep}`);
  }
  counts.sort();
  counts.reverse();
  let order = [];
  for (let s of counts) {
    order.push(s.split('_')[1]);
  }

  console.log(`let mainInfo = ${JSON.stringify(mainInfo, null, 2)};`);
  console.log();
  console.log(`let licensedDependencies = ${JSON.stringify(licensedDependencies, null, 2)};`);
  console.log();
  console.log(`let order = ${JSON.stringify(order)};`);
  console.log();
  console.log("export {mainInfo, licensedDependencies, order};");

  console.error("Done.");
  console.error("========================================== "+(new Date()));
  process.exit(0);
});
